# coding: utf-8
from sqlalchemy import Column, DateTime, MetaData, Table, Text

metadata = MetaData()


t_raw_garmin_data_laps = Table(
    'raw_garmin_data_laps', metadata,
    Column('timestamp', DateTime(True)),
    Column('start_time', DateTime(True)),
    Column('start_position_lat', Text),
    Column('start_position_long', Text),
    Column('end_position_lat', Text),
    Column('end_position_long', Text),
    Column('total_elapsed_time', Text),
    Column('total_timer_time', Text),
    Column('total_distance', Text),
    Column('message_index', Text),
    Column('total_calories', Text),
    Column('enhanced_avg_speed', Text),
    Column('avg_speed', Text),
    Column('event', Text),
    Column('event_type', Text),
    Column('avg_heart_rate', Text),
    Column('max_heart_rate', Text),
    Column('avg_running_cadence', Text),
    Column('max_running_cadence', Text),
    Column('lap_trigger', Text),
    Column('sport', Text),
    Column('activity_id', Text),
    Column('total_strides', Text),
    Column('total_moving_time', Text),
    Column('avg_pos_vertical_speed', Text),
    Column('num_active_lengths', Text),
    Column('unknown_125', Text),
    Column('unknown_126', Text),
    Column('total_cycles', Text),
    Column('avg_cadence', Text),
    Column('max_cadence', Text),
    Column('unknown_27', Text),
    Column('unknown_28', Text),
    Column('unknown_29', Text),
    Column('unknown_30', Text),
    Column('enhanced_max_speed', Text),
    Column('max_speed', Text),
    Column('total_ascent', Text),
    Column('total_descent', Text),
    Column('wkt_step_index', Text),
    Column('sub_sport', Text),
    Column('avg_fractional_cadence', Text),
    Column('max_fractional_cadence', Text),
    Column('unknown_155', Text),
    Column('unknown_145', Text)
)
