# coding: utf-8
from sqlalchemy import Column, DateTime, Integer, MetaData, Table, Text

metadata = MetaData()


t_raw_garmin_data_session = Table(
    'raw_garmin_data_session', metadata,
    Column('activity_id', Text),
    Column('start_time', DateTime(True)),
    Column('timestamp', DateTime(True)),
    Column('sport', Text),
    Column('sub_sport', Text),
    Column('total_timer_time', Text),
    Column('total_elapsed_time', Text),
    Column('total_distance', Text),
    Column('total_cycles', Text),
    Column('total_calories', Text),
    Column('start_position_lat', Text),
    Column('start_position_long', Text),
    Column('message_index', Text),
    Column('enhanced_avg_speed', Text),
    Column('avg_speed', Text),
    Column('first_lap_index', Text),
    Column('num_laps', Text),
    Column('event', Text),
    Column('event_type', Text),
    Column('avg_heart_rate', Text),
    Column('max_heart_rate', Text),
    Column('avg_running_cadence', Text),
    Column('max_running_cadence', Text),
    Column('trigger', Text),
    Column('total_strides', Text),
    Column('total_moving_time', Text),
    Column('avg_pos_vertical_speed', Text),
    Column('unknown_33', Text),
    Column('num_active_lengths', Text),
    Column('unknown_142', Text),
    Column('unknown_157', Text),
    Column('unknown_158', Text),
    Column('avg_cadence', Text),
    Column('max_cadence', Text),
    Column('nec_lat', Text),
    Column('nec_long', Text),
    Column('swc_lat', Text),
    Column('swc_long', Text),
    Column('unknown_110', Text),
    Column('enhanced_max_speed', Text),
    Column('max_speed', Text),
    Column('total_ascent', Text),
    Column('total_descent', Text),
    Column('total_training_effect', Text),
    Column('unknown_81', Text),
    Column('avg_fractional_cadence', Text),
    Column('max_fractional_cadence', Text),
    Column('unknown_38', Text),
    Column('unknown_39', Text),
    Column('unknown_152', Text),
    Column('unknown_151', Text),
    Column('unknown_196', Text),
    Column('unknown_178', Text),
    Column('unknown_184', Text),
    Column('unknown_202', Text),
    Column('temp_id', Integer),
    Column('activity_title', Text),
    Column('description', Text)
)
